version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${REMINDER_DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${REMINDER_DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${REMINDER_DB_PASSWORD}
    volumes:
      - ./.env:/app/.env

  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${REMINDER_DB_NAME}
      - POSTGRES_USER=${REMINDER_DB_USERNAME}
      - POSTGRES_PASSWORD=${REMINDER_DB_PASSWORD}

volumes:
  db_data: