spring:
  config:
    import: optional:file:/app/.env[.properties]

  application:
    name: ReminderApp

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${clientId}
            clientSecret: ${clientSecret}
org:
  quartz:
    scheduler:
      timeZone: Europe/Moscow


