spring:
  config:
    import: optional:file:../../.env[.properties]

  application:
    name: ReminderApp

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${REMINDER_DB_NAME}
    username: ${REMINDER_DB_USERNAME}
    password: ${REMINDER_DB_PASSWORD}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${clientId}
            clientSecret: ${clientSecret}


